version: 2.1

# executors:
#   c-executor:
#     docker:
#       - image: gcc:latest

jobs:
  build:
    # executor: c-executor
    docker:
      - image: gcc:latest
    steps:
      - run:
          # to avoid "detected dubious ownership in repository" when using circleci local
          name: Set safe dir
          command: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run:
          name: List files
          command: ls -la
      - run:
          name: Compile main.c
          command: |
            gcc -o main main.c
      - run:
          name: Run main
          command: ./main

workflows:
  build_and_test:
    jobs:
      - build
